### ISSUE TITLE
problems with eval code

### ISSUE THREAD

**Issue by onwn** [ngchc/deepBoosting#1]
When I run eval.py in  db-gray, 'dn-real-in',  'dn-real-cross', 'dn-blind-color', their results are OK,
but when I try the same thing in 'dn-nonblind-gray', 'dn-blind-gray', it throws following error message:

"
2019-04-04 15:36:40.879050: F tensorflow/core/grappler/costs/op_level_cost_estimator.cc:577] Check failed: iz == filter_shape.dim(in_channel_index).size() (8 vs. 16)
"

there's no further message that indicates where this error happened on outer level.

for it's not a global problem, only happening on such tasks, and the message says some kind of 'filter_shape', I'm wondering if the saved model file or corresponding model code is somewhat wrong.

Could you please check this out?

+) I'm using python=3.6. and tensorflow-gpu=1.12.
also tried python=3.5. and tensorflow-gpu=1.10. as written in your README, but that had the same problem, only the problematic line was "op_level_cost_estimator.cc:599" instaed of 577.

**Comment by ngchc** [comment]
The version of tensorflow might be a reason to this failure. A tested version (in my environment) is 1.4.0. Could you try this early version?

**Comment by llmpass** [comment]
@onwn I got the same issue when I tried to run the inference.py. 
@ngchc I tried on a lot of tf versions: 1.10.0, 1.13.0, all of them failed with the same issue:
Check failed: iz == filter_shape.dim(in_channel_index).size() (6 vs. 8)

**Comment by ngchc** [comment]
@llmpass Could you please try the older version, i.e., tf-1.4.0? The code works well in this version.

**Comment by llmpass** [comment]
@ngchc Thank you. 1.4.0 works for me, just confirmed! @onwn
